/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n8.0.1-31-ge36046790a-20251230"
#endif /* AVUTIL_FFVERSION_H */
